services:
  vaultwarden:
    image: vaultwarden/server:1.32.0
    container_name: vaultwarden
    restart: always
    ports: []
    env_file:
      - .env
    volumes:
      - /data/docker/psw:/data
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true

