services:
  caddy:
    image: caddy:2.9
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "9002:9002"
    volumes:
      - /data/docker/caddy/conf:/etc/caddy
      - /data/docker/caddy/site:/srv
      - /data/docker/caddy/data:/data
      - /data/docker/caddy/config:/config
    networks:
        - proxy-net
    # needed for nextcloud aio
    extra_hosts: ["host.docker.internal:host-gateway"]

networks:
  proxy-net:
    external: true
