services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    container_name: eatsubu-wp-db
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    env_file:
      - .env
    volumes:
      - /data/docker/eatsubu/db:/var/lib/mysql
    restart: always
    ports:
      - 3306
      - 33060
    networks:
      default:
  wordpress:
    image: wordpress:php8.1
    container_name: eatsubu-wp
    volumes:
      - /data/docker/eatsubu/wp:/var/www/html
    env_file:
      - .env
    ports:
      - 9001:80
    networks:
      default:
      proxy-net:
        ipv4_address: 172.19.0.20
    restart: always

networks:
  proxy-net:
    external: true
  default:
