name: adguard
services:
    adguardhome:
        image: adguard/adguardhome:latest
        container_name: adguardhome
        restart: always
        volumes:
            - /data/docker/adguard/workdir:/opt/adguardhome/work
            - /data/docker/adguard/confdir:/opt/adguardhome/conf
        ports:
            - 192.168.0.2:53:53/tcp
            - 192.168.0.2:53:53/udp
            - 192.168.0.2:67:67/udp
            # - 192.168.0.2:68:68/udp
            - 192.168.0.2:6080:6080/tcp
            - 192.168.0.2:6443:443/tcp
            - 192.168.0.2:6443:443/udp
            - 192.168.0.2:3002:3000/tcp
            - 192.168.0.2:853:853/tcp
            - 192.168.0.2:853:853/udp
            - 192.168.0.2:5443:5443/tcp
            - 192.168.0.2:5443:5443/udp
            - 192.168.0.2:6060:6060/tcp

