services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=9443
      - DOCKER_MTU=1500 #optional
    volumes:
      - /data/docker/kasm/data:/opt
      - /data/docker/kasm/profiles:/profiles #optional
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 9443:9443
    networks:
      - proxy-net
    restart: unless-stopped

networks:
  proxy-net:
    external: true
