services:
  samba:
    image: ghcr.io/servercontainers/samba
    container_name: samba
    ports:
      - 139:139/tcp
      - 445:445/tcp
      - 137:137/udp
      - 138:138/udp
    env_file:
      - .env
    volumes:
      - /ext-media/tv:/shares/tv
      - /ext-media/movies:/shares/movies
    restart: always
      