# only settings from config files
services:
  dynamic-dns-netcup-updater:
    container_name: dns-updater
    image: mm28ajos/docker-dynamic-dns-netcup-api:latest
    volumes:
      - /data/docker/dns-updater/config.ini:/usr/src/dynamic-dns-netcup-api/config.ini
      - /data/docker/dns-updater/php.ini:/etc/php/8.2/cli/php.ini
    network_mode: host
    # if you want the container to be verbose, override the default command with this one below
    command: php ./update-docker.php
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
