services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    env_file:
      - .env
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - /data/docker/wireguard:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - proxy-net
    restart: unless-stopped

networks:
  proxy-net:
    external: true